apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jnlp
  name: jnlp
spec:
  containers:
    - image: jenkins/jnlp-slave:3.27-1-alpine
      imagePullPolicy: IfNotPresent
      name: jnlp
      command: [ "tail", "-f", "/dev/null" ]  # Keeps the container running
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
